server:
  port: 8090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/CthulhuUsersDb
    username: CthulhuAdmin
    password: pjdflvbyvfu109
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: true

